apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: esantiagopipelinenetcore 
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: esantiagopipelinenetcore 
    spec:
      containers:
        - name: esantiagopipelinenetcore 
          image: escg2503.azurecr.io/esantiagopipelinenetcore
          ports:
          - containerPort: 80